name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: pwd 

    - name: Install dependencies
      run: apt-get install python3-stdeb fakeroot python-all  dh-python

    - name: Run check
      run: python3 setup.py sdist

    - name: Run distcheck
      run: python3 setup.py --command-packages=stdeb.command bdist_deb
