name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: pwd && ls -la

    - name: Install dependencies
      run: sudo apt-get install python3-stdeb fakeroot python-all  dh-python

    - name: Run check
      run: bash build-deb.sh

